/**
 * CohortShiftSchema
 *
 * Stores an annual snapshot of:
 *   - Every cohort (K70, K71…) and which year-group it belongs to
 *   - Actual allocations at snapshot time
 *
 * One document per academic year (upserted on each shift run).
 */
const mongoose = require('mongoose');

// ------------------------------------------------------------------
// Sub-schema: one cohort row inside a snapshot
// ------------------------------------------------------------------
const CohortRowSchema = new mongoose.Schema({
  _id: false,

  /** e.g. "K70" */
  code: { type: String, required: true },

  /** 4-digit enrollment year, e.g. 2024 */
  enrollmentYear: { type: Number, required: true },

  /** 1-based year in school for this academic year (1 = first year, 2 = second…) */
  yearInSchool: { type: Number, required: true },

  /** "year1" | "year2" | "year3" | "year4_plus" */
  yearGroup: {
    type: String,
    enum: ['year1', 'year2', 'year3', 'year4_plus'],
    required: true
  },

  /** Total students in this cohort (snapshot of DB count) */
  studentCount: { type: Number, default: 0 },

  /** Actual room allocations used (live or at run-time) */
  allocated: { type: Number, default: 0 }
});

// ------------------------------------------------------------------
// Sub-schema: aggregated year-group totals inside a snapshot
// ------------------------------------------------------------------
const YearGroupSummarySchema = new mongoose.Schema({
  _id: false,
  /** Cohort codes that fall into this group this year */
  cohorts:     { type: [String], default: [] },
  allocated:   { type: Number, default: 0 },
  studentCount:{ type: Number, default: 0 }
});

// ------------------------------------------------------------------
// Main schema
// ------------------------------------------------------------------
const CohortShiftSchema = new mongoose.Schema({
  /** "2026-2027" */
  academicYear: {
    type: String,
    required: true,
    unique: true,
    index: true,
    validate: {
      validator: v => /^\d{4}-\d{4}$/.test(v),
      message: 'Academic year must be YYYY-YYYY'
    }
  },

  /** UTC date when this snapshot was computed */
  generatedAt: { type: Date, default: Date.now, index: true },

  /** Whether this was triggered automatically or manually */
  isAutoGenerated: { type: Boolean, default: false },

  /** All cohort rows for this year */
  cohorts: { type: [CohortRowSchema], default: [] },

  /** Aggregated by year-group */
  summary: {
    year1:      { type: YearGroupSummarySchema, default: () => ({}) },
    year2:      { type: YearGroupSummarySchema, default: () => ({}) },
    year3:      { type: YearGroupSummarySchema, default: () => ({}) },
    year4_plus: { type: YearGroupSummarySchema, default: () => ({}) }
  },

  /** Who triggered the shift (admin ObjectId) */
  triggeredBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'students'
  },

  notes: { type: String, default: '' },

  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

CohortShiftSchema.pre('save', function (next) {
  this.updatedAt = new Date();
  next();
});

const CohortShiftModel = mongoose.model('CohortShift', CohortShiftSchema);
module.exports = CohortShiftModel;
