@startuml
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
  BackgroundColor LightGoldenRodYellow
  BorderColor GoldenRod
  FontName Arial
  FontSize 12
}

actor "Sinh viên" as Student
actor "Cán bộ quản lý" as Manager
actor "Hệ thống" as System

(Đăng ký ở và nộp minh chứng) as UC1
(Cấu hình chính sách và tham số) as UC2
(Chạy mô phỏng & thực thi phân bổ) as UC3
(Tra cứu kết quả, khiếu nại) as UC4
(Quản lý danh sách phòng) as UC5
(Thông báo thời gian thực \\\n  và audit log) as UC6

Student --> UC1
Manager --> UC2
Manager --> UC3
Student --> UC4
Manager --> UC5
System --> UC6

@enduml
